#!/bin/sh

echo "aaaaaaaaaaa I'am suiciding ... $*" > /dev/console 

### use kernel module replaced
# echo 0 > /sys/class/gpio/gpio362/value
sudo sh -c 'echo 1 > /sys/module/sunxi_gpiokey/parameters/poweroff'

